export * from './assessment.repository';
export * from './class.repository';
export * from './courseAssignment.repository';
export * from './courseRegistration.repository';
export * from './examSchedule.repository';
export * from './grade.repository';
export * from './question.repository';
export * from './result.repository';
export * from './setting.repository';
export * from './subject.repository';
export * from './user.repository';
export * from './examAttempt.repository';
export * from './courseResult.repository'
export * from './export.repository';